# Generated by Django 4.2.7 on 2023-11-17 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="question",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="subscribe_plan",
        ),
    ]
